# -*- coding: utf-8 -*-
"""
Created on Wed Mar 16 19:14:37 2022

[theme]
base="light"
backgroundColor="#66b2d8"
font="monospace"

@author: NiruSai
"""
[theme]
primaryColor="#919e8b"
backgroundColor="#fef8ef"
secondaryBackgroundColor="#ebd2b9"
textColor="#000000"
